# Generated by Django 3.1.4 on 2020-12-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='journalrejting',
            new_name='journalspagecount',
        ),
    ]
