# Generated by Django 3.1.4 on 2020-12-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='postal_code',
            field=models.CharField(max_length=25),
        ),
    ]
