# Generated by Django 3.1.4 on 2020-12-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201226_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pk'], 'verbose_name': 'Book', 'verbose_name_plural': 'Book'},
        ),
    ]
