# Generated by Django 3.1.4 on 2020-12-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20201226_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk']},
        ),
    ]
