# Generated by Django 3.1.4 on 2020-12-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201226_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-bookrejting']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookrejtin',
            new_name='bookrejting',
        ),
    ]
